/* SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Francesco Maiomascio
 * Generated by tools/generate_abi.py from api/c-abi.json.
 * Pre-release POSIX ABI. See docs/c-api.md for ownership and failure rules.
 * All calls on a handle MUST be serialized by the caller.
 * Non-NULL pointers must be live, aligned and valid for their stated extent.
 * Input/output regions must not overlap. Lengths are bytes; no implicit strlen.
 * NULL spans are permitted only at zero length. No text is NUL-terminated.
 * Reserved fields must be zero. Struct size/version must match exactly.
 * INTERNAL means close/destroy only. No call is async-signal-safe.
 */
#ifndef REPLAI_H
#define REPLAI_H
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct replai_handle replai_handle;
typedef int32_t replai_status;
typedef uint32_t replai_event_kind;
typedef uint32_t replai_style_role;
#define REPLAI_C_ABI_VERSION 1
#define REPLAI_OK 0
#define REPLAI_INVALID_ARGUMENT 1
#define REPLAI_INVALID_UTF8 2
#define REPLAI_INVALID_RANGE 3
#define REPLAI_CAPACITY 4
#define REPLAI_INVALID_STATE 5
#define REPLAI_UNSUITABLE_TERMINAL 6
#define REPLAI_IO 7
#define REPLAI_BUFFER_TOO_SMALL 8
#define REPLAI_ABI_MISMATCH 9
#define REPLAI_BUSY 10
#define REPLAI_INTERNAL 11
#define REPLAI_INVALID_TEXT 12
#define REPLAI_HISTORY_DISABLED 13
#define REPLAI_INVALID_SEQUENCE 14
#define REPLAI_EVENT_NONE 0
#define REPLAI_EVENT_SUBMITTED 1
#define REPLAI_EVENT_INTERRUPTED 2
#define REPLAI_EVENT_END_OF_INPUT 3
#define REPLAI_EVENT_COMPLETION_REQUESTED 4
#define REPLAI_EVENT_EDIT_REJECTED 5
#define REPLAI_ROLE_DEFAULT 0
#define REPLAI_ROLE_STRONG 1
#define REPLAI_ROLE_ACCENT 2
#define REPLAI_ROLE_DIM 3
#define REPLAI_ROLE_SUCCESS 4
#define REPLAI_ROLE_WARNING 5
#define REPLAI_ROLE_ERROR 6
#define REPLAI_PRESENTATION_VERSION 1
#define REPLAI_BLOCK_PARAGRAPH 0
#define REPLAI_BLOCK_HEADING 1
#define REPLAI_BLOCK_FIELD 2
#define REPLAI_BLOCK_LIST 3
#define REPLAI_BLOCK_LITERAL 4
#define REPLAI_BLOCK_STATUS 5
#define REPLAI_BLOCK_SPACER 6
#define REPLAI_BLOCK_TABLE_HEADER 7
#define REPLAI_BLOCK_TABLE_ROW 8
#define REPLAI_APPLIED 0
#define REPLAI_STALE 1
#define REPLAI_WAKE_INPUT 0
#define REPLAI_WAKE_RESIZE 1
#define REPLAI_WAKE_DEADLINE 2
#define REPLAI_WAIT_READY 0
#define REPLAI_WAIT_INPUT 1
/* Creation limits. Zero-initialize, then set struct_size, abi_version and desired limits. */
typedef struct replai_config {
    uint32_t struct_size;
    uint32_t abi_version;
    uint64_t max_input_bytes;
    uint64_t history_entries;
    uint64_t reserved[2];
} replai_config;
/* Poll output. Before EVERY poll/interrupt: zero-initialize and set struct_size and abi_version. */
typedef struct replai_event {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t kind;
    int32_t status;
    uint64_t text_bytes;
    uint64_t cursor_bytes;
    uint64_t reserved[2];
} replai_event;
/* Bounded semantic span; no control escapes. */
typedef struct replai_span {
    uint32_t struct_size;
    uint32_t extension_version;
    const uint8_t * text;
    size_t text_bytes;
    uint32_t role;
    uint32_t reserved;
} replai_span;
/* Bounded composed text, copied during the call. */
typedef struct replai_text {
    uint32_t struct_size;
    uint32_t extension_version;
    const replai_span * spans;
    size_t span_count;
    uint64_t reserved[2];
} replai_text;
/* Flat block. kind selects payload; unused fields must be zero. Table rows follow their header. */
typedef struct replai_block {
    uint32_t struct_size;
    uint32_t extension_version;
    uint32_t kind;
    uint32_t level;
    replai_text text;
    replai_text label;
    const replai_text * cells;
    size_t cell_count;
    uint64_t reserved[2];
} replai_block;
/* Standalone layout; width includes indent. styled is 0 or 1. */
typedef struct replai_render {
    uint32_t struct_size;
    uint32_t extension_version;
    uint32_t columns;
    uint32_t indent;
    uint32_t styled;
    uint32_t reserved;
} replai_render;
/* Revision-bound candidate. label and annotation are display only. */
typedef struct replai_candidate {
    uint32_t struct_size;
    uint32_t extension_version;
    size_t start;
    size_t end;
    const uint8_t * insertion;
    size_t insertion_bytes;
    const uint8_t * label;
    size_t label_bytes;
    const uint8_t * annotation;
    size_t annotation_bytes;
    uint64_t reserved[2];
} replai_candidate;
/* Zero output fields before each query. FD is borrowed; timeout_ms -1 denotes no deadline. */
typedef struct replai_interest {
    uint32_t struct_size;
    uint32_t extension_version;
    uint32_t kind;
    int32_t input_fd;
    int32_t timeout_ms;
    uint32_t reserved;
    uint64_t deadline_ticket;
} replai_interest;
/* Write the exact runtime ABI identity. */
replai_status replai_abi_version(uint32_t * version);
/* Create one owned opaque handle. *out must initially be NULL. Failures leave it unchanged. */
replai_status replai_create(const replai_config * config, replai_handle * * out);
/* Close and release *handle, then set it to NULL, including on cleanup error. NULL is invalid. */
replai_status replai_destroy(replai_handle * * handle);
/* Configure a closed interaction atomically. All three fields are literal UTF-8; continuation is explicit. */
replai_status replai_prompt(replai_handle * handle, const uint8_t * label, size_t label_len, const uint8_t * suffix, size_t suffix_len, const uint8_t * continuation, size_t continuation_len);
/* Borrow caller FDs for this call; own duplicates until terminal outcome/close/destroy. Requires closed state. */
replai_status replai_open(replai_handle * handle, int32_t input_fd, int32_t output_fd);
/* Restore/release terminal duplicates; retain editor/history. Idempotent, including before open. */
replai_status replai_close(replai_handle * handle);
/* Poll bounded ready input, waiting at most 100 ms. Stop at the first event; read-ahead remains with the handle across reopen. Validate event before consuming input. */
replai_status replai_poll(replai_handle * handle, uint32_t timeout_ms, replai_event * event);
/* Deliver a host-observed interrupt and close. Ordinary control flow only; not signal-handler safe. */
replai_status replai_interrupt(replai_handle * handle, replai_event * event);
/* Copy exact UTF-8, no NUL terminator. NULL/0 queries successfully. Too-small writes only required/cursor. */
replai_status replai_draft_copy(replai_handle * handle, uint8_t * buffer, size_t capacity, size_t * required, size_t * cursor);
/* Copy the last submission until next successful open. No submission: INVALID_STATE. Same copy rules as draft_copy. */
replai_status replai_submitted_copy(replai_handle * handle, uint8_t * buffer, size_t capacity, size_t * required);
/* Replace the entire closed draft atomically; cursor moves to end. History and last submission are retained. */
replai_status replai_set_draft(replai_handle * handle, const uint8_t * text, size_t length);
/* Clear closed draft/navigation, retaining admitted history and last submission. */
replai_status replai_clear(replai_handle * handle);
/* Explicit host admission while closed. Oldest entry evicted at configured capacity; no deduplication. */
replai_status replai_history_add(replai_handle * handle, const uint8_t * text, size_t length);
/* Replace a grapheme-aligned byte range while open. Validation failure leaves draft/display unchanged. */
replai_status replai_complete(replai_handle * handle, size_t start, size_t end, const uint8_t * text, size_t length);
/* Write safe UTF-8 with one generic role, then restore draft/cursor. Reject arbitrary control/ANSI data. */
replai_status replai_external_output(replai_handle * handle, uint32_t role, const uint8_t * text, size_t length);
/* Copy a static diagnostic by status using caller storage; no NUL terminator or library text allocation crosses C. */
replai_status replai_status_text(int32_t status, uint8_t * buffer, size_t capacity, size_t * required);
/* Query the separate presentation extension identity. */
replai_status replai_presentation_version(uint32_t * version);
/* Validate/layout before copying. NULL/0 queries exact bytes, never acquires a terminal. */
replai_status replai_document_render(const replai_block * blocks, size_t block_count, const replai_render * options, uint8_t * buffer, size_t capacity, size_t * required);
/* Validate the whole document then coordinate it with the active editor. */
replai_status replai_document_output(replai_handle * handle, const replai_block * blocks, size_t block_count);
/* Configure primary and continuation semantic spans while closed. */
replai_status replai_prompt_composed(replai_handle * handle, const replai_text * primary, const replai_text * continuation);
/* Return coherent draft/cursor and opaque ticket; query/too-small rules match draft_copy. */
replai_status replai_completion_snapshot(replai_handle * handle, uint8_t * buffer, size_t capacity, size_t * required, size_t * cursor, uint64_t * ticket);
/* Install all candidates atomically; stale ticket skips payload validation and writes STALE. */
replai_status replai_completions_present(replai_handle * handle, uint64_t ticket, const replai_candidate * candidates, size_t candidate_count, uint32_t * disposition);
/* Query driven readiness and deadline without waiting. */
replai_status replai_wait_interest(replai_handle * handle, replai_interest * interest);
/* Advance input/resize/deadline, never waits. Event remains ABI 1. */
replai_status replai_advance(replai_handle * handle, uint32_t wake, uint64_t deadline_ticket, replai_event * event);
/* Measure safe single-line UTF-8 under UnicodeNarrow; controls fail. */
replai_status replai_text_cells(const uint8_t * text, size_t text_bytes, size_t * cells);
/* Acquire quiet output while editor is closed; preserves canonical mode and ISIG. */
replai_status replai_output_open(replai_handle * handle, int32_t input_fd, int32_t output_fd);
/* Replace temporary semantic feedback at a host-established line boundary; empty clears. */
replai_status replai_output_feedback(replai_handle * handle, const replai_text * text);
/* Clear/restore output lifetime; discard_input is an explicit 0/1 host policy. */
replai_status replai_output_close(replai_handle * handle, uint32_t discard_input);
/* Copy the producer-authored role sequence; styled is 0/1. Never accepts caller escape sequences. */
replai_status replai_role_sequence(uint32_t role, uint32_t styled, uint8_t * buffer, size_t capacity, size_t * required);
#ifdef __cplusplus
}
#endif
#endif
