// Generated by tools/generate_abi.py; do not edit.

/// ABI constant `REPLAI_C_ABI_VERSION`.
pub const REPLAI_C_ABI_VERSION: u32 = 1;
/// ABI constant `REPLAI_OK`.
pub const REPLAI_OK: i32 = 0;
/// ABI constant `REPLAI_INVALID_ARGUMENT`.
pub const REPLAI_INVALID_ARGUMENT: i32 = 1;
/// ABI constant `REPLAI_INVALID_UTF8`.
pub const REPLAI_INVALID_UTF8: i32 = 2;
/// ABI constant `REPLAI_INVALID_RANGE`.
pub const REPLAI_INVALID_RANGE: i32 = 3;
/// ABI constant `REPLAI_CAPACITY`.
pub const REPLAI_CAPACITY: i32 = 4;
/// ABI constant `REPLAI_INVALID_STATE`.
pub const REPLAI_INVALID_STATE: i32 = 5;
/// ABI constant `REPLAI_UNSUITABLE_TERMINAL`.
pub const REPLAI_UNSUITABLE_TERMINAL: i32 = 6;
/// ABI constant `REPLAI_IO`.
pub const REPLAI_IO: i32 = 7;
/// ABI constant `REPLAI_BUFFER_TOO_SMALL`.
pub const REPLAI_BUFFER_TOO_SMALL: i32 = 8;
/// ABI constant `REPLAI_ABI_MISMATCH`.
pub const REPLAI_ABI_MISMATCH: i32 = 9;
/// ABI constant `REPLAI_BUSY`.
pub const REPLAI_BUSY: i32 = 10;
/// ABI constant `REPLAI_INTERNAL`.
pub const REPLAI_INTERNAL: i32 = 11;
/// ABI constant `REPLAI_INVALID_TEXT`.
pub const REPLAI_INVALID_TEXT: i32 = 12;
/// ABI constant `REPLAI_HISTORY_DISABLED`.
pub const REPLAI_HISTORY_DISABLED: i32 = 13;
/// ABI constant `REPLAI_INVALID_SEQUENCE`.
pub const REPLAI_INVALID_SEQUENCE: i32 = 14;
/// ABI constant `REPLAI_EVENT_NONE`.
pub const REPLAI_EVENT_NONE: u32 = 0;
/// ABI constant `REPLAI_EVENT_SUBMITTED`.
pub const REPLAI_EVENT_SUBMITTED: u32 = 1;
/// ABI constant `REPLAI_EVENT_INTERRUPTED`.
pub const REPLAI_EVENT_INTERRUPTED: u32 = 2;
/// ABI constant `REPLAI_EVENT_END_OF_INPUT`.
pub const REPLAI_EVENT_END_OF_INPUT: u32 = 3;
/// ABI constant `REPLAI_EVENT_COMPLETION_REQUESTED`.
pub const REPLAI_EVENT_COMPLETION_REQUESTED: u32 = 4;
/// ABI constant `REPLAI_EVENT_EDIT_REJECTED`.
pub const REPLAI_EVENT_EDIT_REJECTED: u32 = 5;
/// ABI constant `REPLAI_ROLE_DEFAULT`.
pub const REPLAI_ROLE_DEFAULT: u32 = 0;
/// ABI constant `REPLAI_ROLE_STRONG`.
pub const REPLAI_ROLE_STRONG: u32 = 1;
/// ABI constant `REPLAI_ROLE_ACCENT`.
pub const REPLAI_ROLE_ACCENT: u32 = 2;
/// ABI constant `REPLAI_ROLE_DIM`.
pub const REPLAI_ROLE_DIM: u32 = 3;
/// ABI constant `REPLAI_ROLE_SUCCESS`.
pub const REPLAI_ROLE_SUCCESS: u32 = 4;
/// ABI constant `REPLAI_ROLE_WARNING`.
pub const REPLAI_ROLE_WARNING: u32 = 5;
/// ABI constant `REPLAI_ROLE_ERROR`.
pub const REPLAI_ROLE_ERROR: u32 = 6;
/// ABI constant `REPLAI_PRESENTATION_VERSION`.
pub const REPLAI_PRESENTATION_VERSION: u32 = 1;
/// ABI constant `REPLAI_BLOCK_PARAGRAPH`.
pub const REPLAI_BLOCK_PARAGRAPH: u32 = 0;
/// ABI constant `REPLAI_BLOCK_HEADING`.
pub const REPLAI_BLOCK_HEADING: u32 = 1;
/// ABI constant `REPLAI_BLOCK_FIELD`.
pub const REPLAI_BLOCK_FIELD: u32 = 2;
/// ABI constant `REPLAI_BLOCK_LIST`.
pub const REPLAI_BLOCK_LIST: u32 = 3;
/// ABI constant `REPLAI_BLOCK_LITERAL`.
pub const REPLAI_BLOCK_LITERAL: u32 = 4;
/// ABI constant `REPLAI_BLOCK_STATUS`.
pub const REPLAI_BLOCK_STATUS: u32 = 5;
/// ABI constant `REPLAI_BLOCK_SPACER`.
pub const REPLAI_BLOCK_SPACER: u32 = 6;
/// ABI constant `REPLAI_BLOCK_TABLE_HEADER`.
pub const REPLAI_BLOCK_TABLE_HEADER: u32 = 7;
/// ABI constant `REPLAI_BLOCK_TABLE_ROW`.
pub const REPLAI_BLOCK_TABLE_ROW: u32 = 8;
/// ABI constant `REPLAI_APPLIED`.
pub const REPLAI_APPLIED: u32 = 0;
/// ABI constant `REPLAI_STALE`.
pub const REPLAI_STALE: u32 = 1;
/// ABI constant `REPLAI_WAKE_INPUT`.
pub const REPLAI_WAKE_INPUT: u32 = 0;
/// ABI constant `REPLAI_WAKE_RESIZE`.
pub const REPLAI_WAKE_RESIZE: u32 = 1;
/// ABI constant `REPLAI_WAKE_DEADLINE`.
pub const REPLAI_WAKE_DEADLINE: u32 = 2;
/// ABI constant `REPLAI_WAIT_READY`.
pub const REPLAI_WAIT_READY: u32 = 0;
/// ABI constant `REPLAI_WAIT_INPUT`.
pub const REPLAI_WAIT_INPUT: u32 = 1;
/// Creation limits. Zero-initialize, then set struct_size, abi_version and desired limits.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiConfig {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `abi_version`; see the installed header contract.
    pub abi_version: u32,
    /// ABI field `max_input_bytes`; see the installed header contract.
    pub max_input_bytes: u64,
    /// ABI field `history_entries`; see the installed header contract.
    pub history_entries: u64,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
/// Poll output. Before EVERY poll/interrupt: zero-initialize and set struct_size and abi_version.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiEvent {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `abi_version`; see the installed header contract.
    pub abi_version: u32,
    /// ABI field `kind`; see the installed header contract.
    pub kind: u32,
    /// ABI field `status`; see the installed header contract.
    pub status: i32,
    /// ABI field `text_bytes`; see the installed header contract.
    pub text_bytes: u64,
    /// ABI field `cursor_bytes`; see the installed header contract.
    pub cursor_bytes: u64,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
/// Bounded semantic span; no control escapes.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiSpan {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `extension_version`; see the installed header contract.
    pub extension_version: u32,
    /// ABI field `text`; see the installed header contract.
    pub text: *const u8,
    /// ABI field `text_bytes`; see the installed header contract.
    pub text_bytes: usize,
    /// ABI field `role`; see the installed header contract.
    pub role: u32,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: u32,
}
/// Bounded composed text, copied during the call.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiText {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `extension_version`; see the installed header contract.
    pub extension_version: u32,
    /// ABI field `spans`; see the installed header contract.
    pub spans: *const ReplaiSpan,
    /// ABI field `span_count`; see the installed header contract.
    pub span_count: usize,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
/// Flat block. kind selects payload; unused fields must be zero. Table rows follow their header.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiBlock {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `extension_version`; see the installed header contract.
    pub extension_version: u32,
    /// ABI field `kind`; see the installed header contract.
    pub kind: u32,
    /// ABI field `level`; see the installed header contract.
    pub level: u32,
    /// ABI field `text`; see the installed header contract.
    pub text: ReplaiText,
    /// ABI field `label`; see the installed header contract.
    pub label: ReplaiText,
    /// ABI field `cells`; see the installed header contract.
    pub cells: *const ReplaiText,
    /// ABI field `cell_count`; see the installed header contract.
    pub cell_count: usize,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
/// Standalone layout; width includes indent. styled is 0 or 1.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiRender {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `extension_version`; see the installed header contract.
    pub extension_version: u32,
    /// ABI field `columns`; see the installed header contract.
    pub columns: u32,
    /// ABI field `indent`; see the installed header contract.
    pub indent: u32,
    /// ABI field `styled`; see the installed header contract.
    pub styled: u32,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: u32,
}
/// Revision-bound candidate. label and annotation are display only.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiCandidate {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `extension_version`; see the installed header contract.
    pub extension_version: u32,
    /// ABI field `start`; see the installed header contract.
    pub start: usize,
    /// ABI field `end`; see the installed header contract.
    pub end: usize,
    /// ABI field `insertion`; see the installed header contract.
    pub insertion: *const u8,
    /// ABI field `insertion_bytes`; see the installed header contract.
    pub insertion_bytes: usize,
    /// ABI field `label`; see the installed header contract.
    pub label: *const u8,
    /// ABI field `label_bytes`; see the installed header contract.
    pub label_bytes: usize,
    /// ABI field `annotation`; see the installed header contract.
    pub annotation: *const u8,
    /// ABI field `annotation_bytes`; see the installed header contract.
    pub annotation_bytes: usize,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: [u64; 2],
}
/// Zero output fields before each query. FD is borrowed; timeout_ms -1 denotes no deadline.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplaiInterest {
    /// ABI field `struct_size`; see the installed header contract.
    pub struct_size: u32,
    /// ABI field `extension_version`; see the installed header contract.
    pub extension_version: u32,
    /// ABI field `kind`; see the installed header contract.
    pub kind: u32,
    /// ABI field `input_fd`; see the installed header contract.
    pub input_fd: i32,
    /// ABI field `timeout_ms`; see the installed header contract.
    pub timeout_ms: i32,
    /// ABI field `reserved`; see the installed header contract.
    pub reserved: u32,
    /// ABI field `deadline_ticket`; see the installed header contract.
    pub deadline_ticket: u64,
}
